### PR TITLE
Yawn pull 7 26 2020

### PR DESCRIPTION
**Pull request by TalkingCactus**

### CODE REVIEW

**Comment by TalkingCactus** [comment]
>insert comment about testmerging

**Comment by DameonOwen** [comment]
> > insert comment about testmerging

> insert comment about having a backup branch of master pre-merge

**Comment by TalkingCactus** [comment]
> insert comment about testmerging
 
> > insert comment about having a backup branch of master pre-merge

> > > insert comment about agreeing with making a backup branch

**Comment by DameonOwen** [comment]
> insert comment about testmerging

> > insert comment about having a backup branch of master pre-merge

> > > insert comment about agreeing with making a backup branch

> > > > insert comment about the backup branch having been created

**Comment by DameonOwen** [comment]
Elevators act as if they are empty space, so they suck the atmosphere into themselves and void it. Cannot be added until this is fixed.

**Comment by DameonOwen** [comment]
These UIs look amazing though.

**Comment by TalkingCactus** [comment]
elevators were pulling in air from space since there's a new z level added that the elevator was trying to go into. we're updating from yw's map updates and are going to pull our big stuff over manually

**Review by DameonOwen — APPROVED** [review]
Too big to review, LGTM.

**Pull request merged**
